.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.update()
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'

pages:
  image: julia:1.11
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .julia/compiled
      - .julia/packages
      - sysimage.so  # Cache the precompiled system image
  stage: deploy
  script:
    - julia --project=. -e 'using Pkg; Pkg.add("PackageCompiler");'
    - julia --project=. build_sysimage.jl  # Build the system image
    - julia --sysimage=sysimage.so --project=. -e 'using Pkg; Pkg.instantiate();'
    - julia --sysimage=sysimage.so --project=. docs/make.jl  # Build your documentation
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - main
