.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
pages:
  image: julia:1.9
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git # needed by Documenter
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.update()
        Pkg.develop(PackageSpec(path=pwd()))
        using Documenter: doctest
        using Damysos
        doctest(Damysos)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - main
