name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ["1.10", "1.11"]
    env:
      JULIA_NUM_THREADS: auto
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - name: Run fast tests
        run: julia --color=yes --project=. -e 'using Pkg; Pkg.test(; test_args=["fast"])'
